'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Dr_validation
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dr_profile", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dr_profile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstnameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastnameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private activation_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private app_versionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private emailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private group_numField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private postalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private provider_numField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private specialtyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private telephoneField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Firstname() As String
            Get
                Return Me.FirstnameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstnameField, value) <> true) Then
                    Me.FirstnameField = value
                    Me.RaisePropertyChanged("Firstname")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Lastname() As String
            Get
                Return Me.LastnameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastnameField, value) <> true) Then
                    Me.LastnameField = value
                    Me.RaisePropertyChanged("Lastname")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property activation_code() As String
            Get
                Return Me.activation_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.activation_codeField, value) <> true) Then
                    Me.activation_codeField = value
                    Me.RaisePropertyChanged("activation_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property app_version() As String
            Get
                Return Me.app_versionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.app_versionField, value) <> true) Then
                    Me.app_versionField = value
                    Me.RaisePropertyChanged("app_version")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cityField, value) <> true) Then
                    Me.cityField = value
                    Me.RaisePropertyChanged("city")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.emailField, value) <> true) Then
                    Me.emailField = value
                    Me.RaisePropertyChanged("email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property group_num() As String
            Get
                Return Me.group_numField
            End Get
            Set
                If (Object.ReferenceEquals(Me.group_numField, value) <> true) Then
                    Me.group_numField = value
                    Me.RaisePropertyChanged("group_num")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property postal() As String
            Get
                Return Me.postalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.postalField, value) <> true) Then
                    Me.postalField = value
                    Me.RaisePropertyChanged("postal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property provider_num() As String
            Get
                Return Me.provider_numField
            End Get
            Set
                If (Object.ReferenceEquals(Me.provider_numField, value) <> true) Then
                    Me.provider_numField = value
                    Me.RaisePropertyChanged("provider_num")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property specialty() As String
            Get
                Return Me.specialtyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.specialtyField, value) <> true) Then
                    Me.specialtyField = value
                    Me.RaisePropertyChanged("specialty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property telephone() As String
            Get
                Return Me.telephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.telephoneField, value) <> true) Then
                    Me.telephoneField = value
                    Me.RaisePropertyChanged("telephone")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="messages", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class messages
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private msgsField() As Dr_validation.message
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property msgs() As Dr_validation.message()
            Get
                Return Me.msgsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.msgsField, value) <> true) Then
                    Me.msgsField = value
                    Me.RaisePropertyChanged("msgs")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="message", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class message
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ftp_pwdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ftp_uidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_actionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_couponField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_descriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_typeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_urlField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private message_websiteField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ftp_pwd() As String
            Get
                Return Me.ftp_pwdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ftp_pwdField, value) <> true) Then
                    Me.ftp_pwdField = value
                    Me.RaisePropertyChanged("ftp_pwd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ftp_uid() As String
            Get
                Return Me.ftp_uidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ftp_uidField, value) <> true) Then
                    Me.ftp_uidField = value
                    Me.RaisePropertyChanged("ftp_uid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_action() As String
            Get
                Return Me.message_actionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_actionField, value) <> true) Then
                    Me.message_actionField = value
                    Me.RaisePropertyChanged("message_action")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_coupon() As String
            Get
                Return Me.message_couponField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_couponField, value) <> true) Then
                    Me.message_couponField = value
                    Me.RaisePropertyChanged("message_coupon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_description() As String
            Get
                Return Me.message_descriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_descriptionField, value) <> true) Then
                    Me.message_descriptionField = value
                    Me.RaisePropertyChanged("message_description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_type() As String
            Get
                Return Me.message_typeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_typeField, value) <> true) Then
                    Me.message_typeField = value
                    Me.RaisePropertyChanged("message_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_url() As String
            Get
                Return Me.message_urlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_urlField, value) <> true) Then
                    Me.message_urlField = value
                    Me.RaisePropertyChanged("message_url")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message_website() As String
            Get
                Return Me.message_websiteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.message_websiteField, value) <> true) Then
                    Me.message_websiteField = value
                    Me.RaisePropertyChanged("message_website")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Dr_validation.Icheck_update")>  _
    Public Interface Icheck_update
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Icheck_update/Check_Account", ReplyAction:="http://tempuri.org/Icheck_update/Check_AccountResponse")>  _
        Function Check_Account(ByVal Dr As Dr_validation.dr_profile) As Dr_validation.messages
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/Icheck_update/Check_Account", ReplyAction:="http://tempuri.org/Icheck_update/Check_AccountResponse")>  _
        Function BeginCheck_Account(ByVal Dr As Dr_validation.dr_profile, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndCheck_Account(ByVal result As System.IAsyncResult) As Dr_validation.messages
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Icheck_updateChannel
        Inherits Dr_validation.Icheck_update, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Check_AccountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Dr_validation.messages
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Dr_validation.messages)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Icheck_updateClient
        Inherits System.ServiceModel.ClientBase(Of Dr_validation.Icheck_update)
        Implements Dr_validation.Icheck_update
        
        Private onBeginCheck_AccountDelegate As BeginOperationDelegate
        
        Private onEndCheck_AccountDelegate As EndOperationDelegate
        
        Private onCheck_AccountCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event Check_AccountCompleted As System.EventHandler(Of Check_AccountCompletedEventArgs)
        
        Public Function Check_Account(ByVal Dr As Dr_validation.dr_profile) As Dr_validation.messages Implements Dr_validation.Icheck_update.Check_Account
            Return MyBase.Channel.Check_Account(Dr)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginCheck_Account(ByVal Dr As Dr_validation.dr_profile, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Dr_validation.Icheck_update.BeginCheck_Account
            Return MyBase.Channel.BeginCheck_Account(Dr, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndCheck_Account(ByVal result As System.IAsyncResult) As Dr_validation.messages Implements Dr_validation.Icheck_update.EndCheck_Account
            Return MyBase.Channel.EndCheck_Account(result)
        End Function
        
        Private Function OnBeginCheck_Account(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Dr As Dr_validation.dr_profile = CType(inValues(0),Dr_validation.dr_profile)
            Return Me.BeginCheck_Account(Dr, callback, asyncState)
        End Function
        
        Private Function OnEndCheck_Account(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Dr_validation.messages = Me.EndCheck_Account(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnCheck_AccountCompleted(ByVal state As Object)
            If (Not (Me.Check_AccountCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent Check_AccountCompleted(Me, New Check_AccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub Check_AccountAsync(ByVal Dr As Dr_validation.dr_profile)
            Me.Check_AccountAsync(Dr, Nothing)
        End Sub
        
        Public Overloads Sub Check_AccountAsync(ByVal Dr As Dr_validation.dr_profile, ByVal userState As Object)
            If (Me.onBeginCheck_AccountDelegate Is Nothing) Then
                Me.onBeginCheck_AccountDelegate = AddressOf Me.OnBeginCheck_Account
            End If
            If (Me.onEndCheck_AccountDelegate Is Nothing) Then
                Me.onEndCheck_AccountDelegate = AddressOf Me.OnEndCheck_Account
            End If
            If (Me.onCheck_AccountCompletedDelegate Is Nothing) Then
                Me.onCheck_AccountCompletedDelegate = AddressOf Me.OnCheck_AccountCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCheck_AccountDelegate, New Object() {Dr}, Me.onEndCheck_AccountDelegate, Me.onCheck_AccountCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
